
#
# Deploy the Kube-Hunter job to scan for vulnerabilties.
#

# ------------------- Job ------------------- #

apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
  labels:
    app: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter 
        command: ["python", "kube-hunter.py"]
        args: ["--pod", "--internal"]
      restartPolicy: Never
  backoffLimit: 4