---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: mongo-backup
  name: mgob-config
  namespace: default
data:
  database1.yaml: |
    target:
      host: "mongo-0.mongo-svc.default.svc.cluster.local,mongo-1.mongo-svc.default.svc.cluster.local,mongo-2.mongo-svc.default.svc.cluster.local"
      port: 27017
      # !CHANGE THIS! To your databse name you wish to backup
      database: "<Change_Me>"
    scheduler:
      cron: "0 0 * * *"
      retention: 7
      timeout: 60
    azure:
      # !CHANGE THIS! To your real container name within the storage account
      containerName: "<Change_Me>"
      # !CHANGE THIS! To your real connection string for the storage account 
      connectionString: "<Change_Me>"
