#
# Deploy the front end Angular UI microservice in Kubernetes
#

# ------------------- Scaling Policy ------------------- #

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90

---

# ------------------- Deployment ------------------- #

kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  labels:
    app: frontend
    role: frontend
spec:
  replicas: 1
  selector:

  
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        role: frontend
    spec:
      containers:
      - name: frontend-pods

        # !CHANGE THIS! To your real image reference for the frontend 
        image: aksregistry.azurecr.io/frontend:latest
        ports:
        - containerPort: 80

        command: ["/bin/sh", "main.sh"]

        env:       
        - name: API_URL
          value: admin.cloudpea.co.uk/api
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 20

        resources:
          requests:
            memory: "50M"
            cpu: "0.125"